// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAGr49s8-jP5bwusr5xcL7e18fVFkyFlg',
    appId: '1:294690217987:web:783ce9b2b984e7f1cdee36',
    messagingSenderId: '294690217987',
    projectId: 'diet-recommendation-fea46',
    authDomain: 'diet-recommendation-fea46.firebaseapp.com',
    storageBucket: 'diet-recommendation-fea46.appspot.com',
    measurementId: 'G-PCT88Q5YTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFT794WLenZuRF9h7t87rDR1kF4qSKWY4',
    appId: '1:294690217987:android:e15177f43ab0929bcdee36',
    messagingSenderId: '294690217987',
    projectId: 'diet-recommendation-fea46',
    storageBucket: 'diet-recommendation-fea46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ4GsFwBN9ikhIIDki-BAEclKbarF7IUs',
    appId: '1:294690217987:ios:e4b8f7ba8c70f3f8cdee36',
    messagingSenderId: '294690217987',
    projectId: 'diet-recommendation-fea46',
    storageBucket: 'diet-recommendation-fea46.appspot.com',
    iosBundleId: 'com.example.dietRecomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ4GsFwBN9ikhIIDki-BAEclKbarF7IUs',
    appId: '1:294690217987:ios:e4b8f7ba8c70f3f8cdee36',
    messagingSenderId: '294690217987',
    projectId: 'diet-recommendation-fea46',
    storageBucket: 'diet-recommendation-fea46.appspot.com',
    iosBundleId: 'com.example.dietRecomm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAGr49s8-jP5bwusr5xcL7e18fVFkyFlg',
    appId: '1:294690217987:web:acde785f0e7ce52ecdee36',
    messagingSenderId: '294690217987',
    projectId: 'diet-recommendation-fea46',
    authDomain: 'diet-recommendation-fea46.firebaseapp.com',
    storageBucket: 'diet-recommendation-fea46.appspot.com',
    measurementId: 'G-W67VM64X9Q',
  );
}
